# Generated by Django 4.2.5 on 2023-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='built_in_plan_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_sizes',
            field=models.JSONField(),
        ),
    ]
