# Generated by Django 4.2.5 on 2023-09-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_tier_built_in_plan_info_alter_tier_thumbnail_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='built_in_plan_info',
        ),
    ]
