# Generated by Django 4.2.5 on 2023-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_remove_tier_built_in_plan_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_sizes',
            field=models.JSONField(default=list),
        ),
    ]
