# Generated by Django 4.2.5 on 2023-09-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_alter_tier_thumbnail_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tier',
        ),
    ]
